### ISSUE TITLE
DuplicateKeyError with upsert in tweets collection

### ISSUE THREAD

**Issue by marcdumon** [marcdumon/twitter_analytics#4]
At the near end of a (long) scraping session, I received a DuplicateKeyError from the tweets-collection. 
The tweet stored on the tweets-collection with tweet_id '1239500620438044674' was created on 2020-07-12 05:34:06 (from _id +2h) by user 'wduyck'. The last time that user was seen in the log is at 2020-07-12 05:40:30. 
Questions:

1.  why does a DuplicateKeyError occurs with upsert? The only unique key is user_id (and _id). Should mongodb not just update the tweet?
2. is it possible that 2 different tweets, from 2 different users (wduyck and ???) have the same tweet_id? Again, why didn't it get updated?

**Here's the error:**
> Traceback (most recent call last):
  File "main.py", line 20, in <module>
    scrape_users_tweets_profile(resume=resume, processes=processes, max_delay=max_delay)
  File "/media/Development/Twitter_Analytics/src/business/scraping_controller.py", line 62, in scrape_users_tweets_profile
    result = pool.starmap(scrape_manager, usernames_pq)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/media/Development/Twitter_Analytics/src/business/scraping_controller.py", line 78, in scrape_manager
    if SCRAPE_TWEETS: scrape_a_user_tweets(username, proxy_queue)
  File "/media/Development/Twitter_Analytics/src/business/scraping_controller.py", line 130, in scrape_a_user_tweets
    save_tweets(tweets_df)
  File "/media/Development/Twitter_Analytics/src/database/twitter_facade.py", line 104, in save_tweets
    q_update_a_tweet(row.to_dict()) if update else q_save_a_tweet(row.to_dict())
  File "/media/Development/Twitter_Analytics/src/database/tweet_queries.py", line 86, in q_update_a_tweet
    result = collection.update_one(f, u, upsert=True)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/collection.py", line 1003, in update_one
    session=session),
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/collection.py", line 856, in _update_retryable
    _update, session)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/collection.py", line 852, in _update
    retryable_write=retryable_write)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/collection.py", line 823, in _update
    _check_write_command_response(result)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
**pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: twitter_database.tweets index: tweet_id_1 dup key: { : "1239500620438044674" }**

**Last time user 'wduyck' was seen:**
>2020-07-12 05:40:29: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: janbriersgouv : 2020-06-03 - 2020-06-09 with proxy {'ip': '81.201.60.130', 'port': '80'}
2020-07-12 05:40:29: [scraping_controller.py         scrape_a_user_tweets:132]:  [WARNING]: Put back proxy {'ip': '181.118.167.104', 'port': '80'}
2020-07-12 05:40:29: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 8
2020-07-12 05:40:29: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: colebundersgaby : 2020-05-06 - 2020-05-12 with proxy {'ip': '40.65.136.31', 'port': '8080'}
**2020-07-12 05:40:30: [scraping_controller.py         scrape_a_user_tweets:129]:  [INFO   ]: Saving 21 tweets for wduyck. 2020-06-24 - 2020-06-28**
2020-07-12 05:40:30: [scraping_controller.py         scrape_a_user_tweets:132]:  [WARNING]: Put back proxy {'ip': '178.63.41.235', 'port': '9999'}
2020-07-12 05:40:30: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 8
2020-07-12 05:40:30: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: karl_drabbe : 2020-01-01 - 2020-01-07 with proxy {'ip': '88.199.21.76', 'port': '80'}
2020-07-12 05:40:31: [scraping_controller.py         scrape_a_user_tweets:129]:  [INFO   ]: Saving 1 tweets for kristofcalvo. 2020-06-24 - 2020-06-28 
2020-07-12 05:40:31: [scraping_controller.py         scrape_a_user_tweets:132]:  [WARNING]: Put back proxy {'ip': '159.203.44.177', 'port': '3128'}

**Here's the log since 15 min before the error**
>2020-07-12 09:40:07: [scraping_controller.py         scrape_a_user_tweets:160]:  [ERROR  ]: ClientOSError Error for username krisremels. 2020-06-10 - 2020-06-16 - Fail counter = 5
2020-07-12 09:40:07: [scraping_controller.py         scrape_a_user_tweets:161]:  [ERROR  ]: [Errno 104] Connection reset by peer
2020-07-12 09:40:33: [scraping_controller.py         scrape_a_user_tweets:143]:  [ERROR  ]: Put back proxy {'ip': '182.23.103.6', 'port': '3137'} after ValueError Error for username elhammouchiothm. 2020-06-17 - 2020-06-23
2020-07-12 09:40:33: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 35
2020-07-12 09:40:33: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: elhammouchiothm : 2020-06-24 - 2020-06-28 with proxy {'ip': '52.179.18.244', 'port': '8080'}
CRITICAL:root:twint.get:User:503, message='Service Unavailable', url=URL('http://52.179.18.244:8080')
2020-07-12 09:40:36: [scraping_controller.py         scrape_a_user_tweets:140]:  [ERROR  ]: ValueError Error for username elhammouchiothm. 2020-06-24 - 2020-06-28 - Fail counter = 1
2020-07-12 09:40:36: [scraping_controller.py         scrape_a_user_tweets:141]:  [ERROR  ]: Cannot find twitter account with name = elhammouchiothm
2020-07-12 09:40:46: [scraping_controller.py         scrape_a_user_tweets:143]:  [ERROR  ]: Put back proxy {'ip': '52.179.18.244', 'port': '8080'} after ValueError Error for username elhammouchiothm. 2020-06-24 - 2020-06-28
2020-07-12 09:40:46: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 35
2020-07-12 09:40:46: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: elhammouchiothm : 2020-06-24 - 2020-06-28 with proxy {'ip': '37.1.202.147', 'port': '3128'}
2020-07-12 09:40:53: [scraping_controller.py         scrape_a_user_tweets:132]:  [WARNING]: Put back proxy {'ip': '37.1.202.147', 'port': '3128'}
2020-07-12 09:40:57: [scraping_controller.py         scrape_a_user_tweets:163]:  [ERROR  ]: Put back proxy {'ip': '54.39.85.228', 'port': '3128'} after ClientOSError Error for username krisremels. 2020-06-10 - 2020-06-16
2020-07-12 09:40:57: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 36
2020-07-12 09:40:57: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: krisremels : 2020-06-17 - 2020-06-23 with proxy {'ip': '54.37.131.97', 'port': '3128'}
2020-07-12 09:41:19: [scraping_controller.py         scrape_a_user_tweets:129]:  [INFO   ]: Saving 313 tweets for krisremels. 2020-06-17 - 2020-06-23 
2020-07-12 09:41:20: [scraping_controller.py         scrape_a_user_tweets:132]:  [WARNING]: Put back proxy {'ip': '54.37.131.97', 'port': '3128'}
2020-07-12 09:41:20: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 36
2020-07-12 09:41:20: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: krisremels : 2020-06-24 - 2020-06-28 with proxy {'ip': '139.99.90.100', 'port': '8080'}
2020-07-12 09:41:26: [scraping_controller.py         scrape_a_user_tweets:170]:  [ERROR  ]: TimeoutError Error for username johanlievens_. 2020-06-17 - 2020-06-23 - Fail counter = 1
2020-07-12 09:41:26: [scraping_controller.py         scrape_a_user_tweets:171]:  [ERROR  ]: 
2020-07-12 09:41:36: [scraping_controller.py         scrape_a_user_tweets:173]:  [ERROR  ]: Put back proxy {'ip': '77.79.187.111', 'port': '8080'} after TimeoutError Error for username johanlievens_. 2020-06-17 - 2020-06-23
2020-07-12 09:41:36: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 36
2020-07-12 09:41:36: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: johanlievens_ : 2020-06-17 - 2020-06-23 with proxy {'ip': '103.22.248.59', 'port': '61661'}
CRITICAL:root:twint.get:User:
2020-07-12 09:43:20: [scraping_controller.py         scrape_a_user_tweets:140]:  [ERROR  ]: ValueError Error for username krisremels. 2020-06-24 - 2020-06-28 - Fail counter = 1
2020-07-12 09:43:20: [scraping_controller.py         scrape_a_user_tweets:141]:  [ERROR  ]: Cannot find twitter account with name = krisremels
2020-07-12 09:43:30: [scraping_controller.py         scrape_a_user_tweets:143]:  [ERROR  ]: Put back proxy {'ip': '139.99.90.100', 'port': '8080'} after ValueError Error for username krisremels. 2020-06-24 - 2020-06-28
2020-07-12 09:43:30: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 36
2020-07-12 09:43:30: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: krisremels : 2020-06-24 - 2020-06-28 with proxy {'ip': '81.144.138.35', 'port': '3128'}
CRITICAL:root:twint.get:User:
2020-07-12 09:43:36: [scraping_controller.py         scrape_a_user_tweets:140]:  [ERROR  ]: ValueError Error for username johanlievens_. 2020-06-17 - 2020-06-23 - Fail counter = 2
2020-07-12 09:43:36: [scraping_controller.py         scrape_a_user_tweets:141]:  [ERROR  ]: Cannot find twitter account with name = johanlievens_
2020-07-12 09:43:56: [scraping_controller.py         scrape_a_user_tweets:143]:  [ERROR  ]: Put back proxy {'ip': '103.22.248.59', 'port': '61661'} after ValueError Error for username johanlievens_. 2020-06-17 - 2020-06-23
2020-07-12 09:43:56: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 36
2020-07-12 09:43:56: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: johanlievens_ : 2020-06-17 - 2020-06-23 with proxy {'ip': '54.38.234.81', 'port': '3128'}
2020-07-12 09:43:57: [scraping_controller.py         scrape_a_user_tweets:132]:  [WARNING]: Put back proxy {'ip': '54.38.234.81', 'port': '3128'}
2020-07-12 09:43:57: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 36
2020-07-12 09:43:57: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: johanlievens_ : 2020-06-24 - 2020-06-28 with proxy {'ip': '159.203.44.177', 'port': '3128'}
CRITICAL:root:twint.get:User:Cannot connect to host 159.203.44.177:3128 ssl:True [Connect call failed ('159.203.44.177', 3128)]
2020-07-12 09:43:57: [scraping_controller.py         scrape_a_user_tweets:140]:  [ERROR  ]: ValueError Error for username johanlievens_. 2020-06-24 - 2020-06-28 - Fail counter = 1
2020-07-12 09:43:57: [scraping_controller.py         scrape_a_user_tweets:141]:  [ERROR  ]: Cannot find twitter account with name = johanlievens_
2020-07-12 09:44:07: [scraping_controller.py         scrape_a_user_tweets:143]:  [ERROR  ]: Put back proxy {'ip': '159.203.44.177', 'port': '3128'} after ValueError Error for username johanlievens_. 2020-06-24 - 2020-06-28
2020-07-12 09:44:07: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 36
2020-07-12 09:44:07: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: johanlievens_ : 2020-06-24 - 2020-06-28 with proxy {'ip': '136.244.110.197', 'port': '8080'}
2020-07-12 09:44:08: [scraping_controller.py         scrape_a_user_tweets:132]:  [WARNING]: Put back proxy {'ip': '136.244.110.197', 'port': '8080'}
2020-07-12 09:47:45: [scraping_controller.py         scrape_a_user_tweets:170]:  [ERROR  ]: TimeoutError Error for username krisremels. 2020-06-24 - 2020-06-28 - Fail counter = 2
2020-07-12 09:47:45: [scraping_controller.py         scrape_a_user_tweets:171]:  [ERROR  ]: 
2020-07-12 09:48:05: [scraping_controller.py         scrape_a_user_tweets:173]:  [ERROR  ]: Put back proxy {'ip': '81.144.138.35', 'port': '3128'} after TimeoutError Error for username krisremels. 2020-06-24 - 2020-06-28
2020-07-12 09:48:05: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 37
2020-07-12 09:48:05: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: krisremels : 2020-06-24 - 2020-06-28 with proxy {'ip': '178.63.41.235', 'port': '9999'}
CRITICAL:root:twint.get:User:
2020-07-12 09:50:05: [scraping_controller.py         scrape_a_user_tweets:140]:  [ERROR  ]: ValueError Error for username krisremels. 2020-06-24 - 2020-06-28 - Fail counter = 3
2020-07-12 09:50:05: [scraping_controller.py         scrape_a_user_tweets:141]:  [ERROR  ]: Cannot find twitter account with name = krisremels
2020-07-12 09:50:35: [scraping_controller.py         scrape_a_user_tweets:143]:  [ERROR  ]: Put back proxy {'ip': '178.63.41.235', 'port': '9999'} after ValueError Error for username krisremels. 2020-06-24 - 2020-06-28
2020-07-12 09:50:35: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 37
2020-07-12 09:50:35: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: krisremels : 2020-06-24 - 2020-06-28 with proxy {'ip': '78.47.119.22', 'port': '3129'}
CRITICAL:root:twint.get:User:
2020-07-12 09:52:35: [scraping_controller.py         scrape_a_user_tweets:140]:  [ERROR  ]: ValueError Error for username krisremels. 2020-06-24 - 2020-06-28 - Fail counter = 4
2020-07-12 09:52:35: [scraping_controller.py         scrape_a_user_tweets:141]:  [ERROR  ]: Cannot find twitter account with name = krisremels
2020-07-12 09:53:15: [scraping_controller.py         scrape_a_user_tweets:143]:  [ERROR  ]: Put back proxy {'ip': '78.47.119.22', 'port': '3129'} after ValueError Error for username krisremels. 2020-06-24 - 2020-06-28
2020-07-12 09:53:15: [scraping_controller.py         scrape_a_user_tweets:122]:  [INFO   ]: Len proxy queue = 37
2020-07-12 09:53:15: [scraping_controller.py         scrape_a_user_tweets:125]:  [INFO   ]: Start scraping tweets for: krisremels : 2020-06-24 - 2020-06-28 with proxy {'ip': '178.62.15.31', 'port': '3128'}
CRITICAL:root:twint.get:User:
2020-07-12 09:55:15: [scraping_controller.py         scrape_a_user_tweets:140]:  [ERROR  ]: ValueError Error for username krisremels. 2020-06-24 - 2020-06-28 - Fail counter = 5
2020-07-12 09:55:15: [scraping_controller.py         scrape_a_user_tweets:141]:  [ERROR  ]: Cannot find twitter account with name = krisremels
2020-07-12 09:56:05: [scraping_controller.py         scrape_a_user_tweets:143]:  [ERROR  ]: Put back proxy {'ip': '178.62.15.31', 'port': '3128'} after ValueError Error for username krisremels. 2020-06-24 - 2020-06-28

**Comment by marcdumon** [comment]
**and some other ones**
From username: mamiracoli
>class 'pymongo.errors.DuplicateKeyError'>
(<class 'pymongo.errors.DuplicateKeyError'>, DuplicateKeyError('E11000 duplicate key error collection: twitter_database.tweets index: tweet_id_1 dup key: { :**"272796629315231744"** }'), <traceback object at 0x7fa7908ccb90>)

From username: jonggroen
><class 'pymongo.errors.DuplicateKeyError'>
(<class 'pymongo.errors.DuplicateKeyError'>, DuplicateKeyError('E11000 duplicate key error collection: twitter_database.tweets index: tweet_id_1 dup key: { : **"159022993824157697"** }'), <traceback object at 0x7fc867b83410>)

From username: mamiracoli
><class 'pymongo.errors.DuplicateKeyError'>
(<class 'pymongo.errors.DuplicateKeyError'>, DuplicateKeyError('E11000 duplicate key error collection: twitter_database.tweets index: tweet_id_1 dup key: { : **"167376171531632640"** }'), <traceback object at 0x7fc8646d71e0>)

**Comment by marcdumon** [comment]
>Traceback (most recent call last):
  File "main.py", line 22, in <module>
    scrape_users_tweets_profile(resume=resume, processes=processes, max_delay=max_delay)
  File "/media/Development/Twitter_Analytics/src/business/scraping_controller.py", line 45, in scrape_users_tweets_profile
    result = pool.starmap(scrape_manager, usernames_pq)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/media/Development/Twitter_Analytics/src/business/scraping_controller.py", line 67, in scrape_manager
    if SCRAPE_TWEETS: scrape_a_user_tweets(username, proxy_queue)
  File "/media/Development/Twitter_Analytics/src/business/scraping_controller.py", line 123, in scrape_a_user_tweets
    save_tweets(tweets_df)
  File "/media/Development/Twitter_Analytics/src/database/twitter_facade.py", line 105, in save_tweets
    q_update_a_tweet(row.to_dict()) if update else q_save_a_tweet(row.to_dict())
  File "/media/Development/Twitter_Analytics/src/database/tweet_queries.py", line 86, in q_update_a_tweet
    result = collection.update_one(f, u, upsert=True)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/collection.py", line 1003, in update_one
    session=session),
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/collection.py", line 856, in _update_retryable
    _update, session)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1491, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
    return func(session, sock_info, retryable)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/collection.py", line 852, in _update
    retryable_write=retryable_write)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/collection.py", line 823, in _update
    _check_write_command_response(result)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/helpers.py", line 221, in _check_write_command_response
    _raise_last_write_error(write_errors)
  File "/home/md/Miniconda3/envs/ai/lib/python3.7/site-packages/pymongo/helpers.py", line 202, in _raise_last_write_error
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: twitter_database.tweets index: tweet_id_1 dup key: { : "1282678353171030021" }

**Comment by marcdumon** [comment]
Starting to debug by adding exception in q_update_a_tweet.

**Comment by marcdumon** [comment]
This error is indeed caused by updating an already existing document. 

tweet doc:
>2020-07-15 16:39:01: [tweet_queries.py                   q_update_a_tweet:92 ]:  [ERROR  ]: {'tweet_id': '1278713597988868096', 'conversation_id': '1278708784077123586', 'user_id': '52359720', 'username': 'saidbataray', 'name': 'Saïd Bataray', 'created_at': 1593704053000, 'datetime': Timestamp('2020-07-02 17:34:13'), 'date': '2020-07-02', 'time': '17:34:13', 'timezone': '+0200', 'day': 4, 'hour': '17', 'tweet': 'Geen idee wat jullie niet zien...', 'hashtags': [], 'cashtags': [], 'reply_to': [{'user_id': '52359720', 'username': 'saidbataray'}, {'user_id': '28069072', 'username': 'krisremels'}, {'user_id': '1010768934', 'username': 'vevadan'}, {'user_id': '1132582584171544577', 'username': 'jjverhels'}], 'is_reply': True, 'quote_url': '', 'link': 'https://twitter.com/SaidBataray/status/1278713597988868096', 'retweet': False, 'nlikes': 0, 'nreplies': 1, 'nretweets': 0, 'search': 'None', 'source': '', 'near': '', 'geo': '', 'place': '', 'user_rt_id': '', 'user_rt': '', 'retweet_id': '', 'retweet_date': '', 'translate': '', 'trans_src': '', 'trans_dest': ''}           

On the database:
>{
    "_id": {
        "$oid": "5f0f150534079452e02ac44c"
    },
    "tweet_id": "1278713597988868096",
    "cashtags": [],
    "conversation_id": "1278708784077123586",
    "created_at": {
        "$numberLong": "1593704053000"
    },
    "date": "2020-07-02",
    "datetime": {
        "$date": "2020-07-02T17:34:13.000Z"
    },
    "day": 4,
    "geo": "",
    "hashtags": [],
    "hour": "17",
    "is_reply": true,
    "link": "https://twitter.com/SaidBataray/status/1278713597988868096",
    "name": "Saïd Bataray",
    "near": "",
    "nlikes": 0,
    "nreplies": 1,
    "nretweets": 0,
    "place": "",
    "quote_url": "",
    "reply_to": [{
        "user_id": "52359720",
        "username": "saidbataray"
    }, {
        "user_id": "28069072",
        "username": "krisremels"
    }, {
        "user_id": "1010768934",
        "username": "vevadan"
    }, {
        "user_id": "1132582584171544577",
        "username": "jjverhels"
    }],
    "retweet": false,
    "retweet_date": "",
    "retweet_id": "",
    "search": "None",
    "source": "",
    "time": "17:34:13",
    "timezone": "+0200",
    "trans_dest": "",
    "trans_src": "",
    "translate": "",
    "tweet": "Geen idee wat jullie niet zien...",
    "user_id": "52359720",
    "user_rt": "",
    "user_rt_id": "",
    "username": "saidbataray"
}

Error message:                                                                                                         
>2020-07-15 16:39:01: [tweet_queries.py                   q_update_a_tweet:93 ]:  [ERROR  ]: E11000 duplicate key error collection: twitter_database.tweets index: tweet_id_1 dup key: { : "1278713597988868096" }

**Comment by marcdumon** [comment]
Also many DuplicateKeyError when scraping profiles.
Example:

><class 'KeyError'>
(<class 'KeyError'>, KeyError('user_id'), <traceback object at 0x7f09d2bd7d20>)

**Comment by marcdumon** [comment]
Solution:
- I upgraded mongodb to 4.2.8 with the same results
- I changed multi threading to multiprocess  `with mp.pool.ThreadPool(processes=processes) as pool:` to `with mp.Pool(processes=processes) as pool:`

**Comment by marcdumon** [comment]
Using multi process iso threading gives much less errors during scraping in general and haven't seen the DuplicateKeyError anymore!
